name: smtpd
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.0
  logging_appenders: ^1.0.0
  meta: ^1.3.0
  freezed_annotation: ^0.14.0
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
  build_runner: ^1.10.0
  freezed: ^0.14.0+1
