name: smtpd
description: SMTP Server library for dart. Meant as a simple way to receive emails behind a postfix server.
version: 0.2.0
homepage: https://github.com/authpass/smtpd.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.2
  logging_appenders: ^1.0.0
  meta: ^1.8.0
  freezed_annotation: ">=2.0.0 <3.0.0"
  collection: ^1.16.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.21.3
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
