name: smtpd
description: SMTP Server library for dart. Meant as a simple way to receive emails behind a postfix server.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  logging: ^0.11.4
  logging_appenders: ^0.4.2+3
  meta: ^1.2.2
  freezed_annotation: ^0.11.0

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
  build_runner: ^1.10.0
  freezed: ^0.11.4
